on: push # 触发此文件运行的条件
name: CI/CD # 此工作流程（workflow）的名字
jobs:
  FTP-Deploy-Action:
    name: CI&CD # 此任务（job）的名字
    runs-on: ubuntu-latest # 运行环境
    steps:
      - uses: actions/checkout@master # 切换分支到main
        with:
          fetch-depth: 2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2.1.4 # 使用node环境
        with:
          node-version: '18.x' # 版本12

      # - name: Cache node modules
      #   id: cache # 缓存id
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules # 缓存名字
      #   with:
      #     path: node_modules # 缓存路径
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }} # 缓存标识

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        # if: steps.cache.outputs.cache-hit != 'true' # 如果没有缓存的话
        run: pnpm i # 安装依赖

      - name: Build Packages
        run: pnpm run build #  打包文件
        
      # # 如果FTP-Deploy-Action出现，Dirty repository: Having uncommitted changes. 问题时，使用以下注释步骤解决问题
      # - name: reset git
      #   run: git reset --hard

      # - name: FTP-Deploy-Action
      #   uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #   with:
      #     ftp-server: sftp://${{ secrets.FTP_IP }}/usr/local/src/pre/home # 服务器地址和端口（可以填域名，不过我服务器做了全站加速会导向加速结点的IP，所以只能用服务器的IP）
      #     ftp-username: ${{ secrets.FTP_USERNAME }} # FTP用户名
      #     ftp-password: ${{ secrets.FTP_PASSWORD }} # FTP密码
      #     git-ftp-args: --insecure # （如果是FTP连接的话--insecure不用加）
      #     local-dir: ./.vitepress/dist # 选择哪些文件要部署到服务器，这个选项在这里选了之后，要在.git-ftp-include中添加相应的路径

